-- AlterTable: make ip and porta nullable
ALTER TABLE "Balanca" ALTER COLUMN "ip" DROP NOT NULL;
ALTER TABLE "Balanca" ALTER COLUMN "porta" DROP DEFAULT;
ALTER TABLE "Balanca" ALTER COLUMN "porta" DROP NOT NULL;

-- AlterTable: add serial and metadata columns
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "fabricante"      TEXT NOT NULL DEFAULT 'Toledo';
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "modelo"          TEXT;
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "tipoComunicacao" TEXT NOT NULL DEFAULT 'HTTP';
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "portaCom"        TEXT;
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "baudRate"        INTEGER NOT NULL DEFAULT 4800;
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "dataBits"        INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "paridade"        TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "stopBits"        INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Balanca" ADD COLUMN IF NOT EXISTS "protocoloSerial" TEXT NOT NULL DEFAULT 'P05';
